version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: laundry-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laundry_db
      MYSQL_USER: laundryuser
      MYSQL_PASSWORD: laundrypass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d  # For initialization scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    container_name: laundry-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=laundry_db
      - DB_USERNAME=laundryuser
      - DB_PASSWORD=laundrypass
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs  # For application logs

  # Frontend web application (can be added later)
  # web:
  #   build: ./frontend
  #   container_name: laundry-web
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

volumes:
  mysql-data:
    driver: local